Add linters
Laylooo/My_Portfolio pull request #9
Opened 2021-07-26 17:47 UTC by Laylooo

2021-07-26 22:27 UTC, arslanbisharat requested changes
# Changes Requested , 

Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-26 22:27 UTC, arslanbisharat commented on js/main.js
> +});
- [ ] When the user click (or tap) the hamburger button, the mobile menu appears.
- [ ] When the user click (or tap) the close (X) button, the mobile menu disappear.
- [ ] When the user click (or tap) any option of the mobile menu, the mobile menu disappear.

2021-07-26 23:45 UTC, Spayco reviewed
Hello 👋,

This is an additional review as a result of the second opinion request.

Can you explain more about how the CR didn't tell you what to do? I can see the changes that should be done:

> - [ ]  When the user click (or tap) the hamburger button, the mobile menu appears.
> - [ ]  When the user click (or tap) the close (X) button, the mobile menu disappear.
> - [ ]  When the user click (or tap) any option of the mobile menu, the mobile menu disappear.

If you mean to walk you through the steps to fix the code, please note that CRs are not supposed to give you ways to fix things, they are only here to do code reviews, if you're stuck on something and need help, please ask the question on [Discourse](https://questions.microverse.org/), or [schedule a meeting with a Senior CR](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-#), but I highly recommend you try to see how to fix the issue few times before going there, so you learn debugging skills!

I can see that the requirements are missing the why element though, so I'll make sure the CR knows about it!

Best of luck with future projects, keep rocking 🚀!

2021-07-27 15:31 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @Laylooo @mateo951  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

![shine team](https://user-images.githubusercontent.com/60631456/127182752-44c69fc2-2a7c-4345-a824-9367695b8aa3.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-27 15:35 UTC, merged